import type { RuleDefinition } from "../domain/types";

export const makeupCertificationV1 = [
  {
    id: "adult-only",
    field: "isAdult",
    operator: "equals",
    expected: true,
    effect: "hard_fail",
    reason: "This pilot is available to adults only.",
  },
  {
    id: "matches-required-sex",
    field: "matchesRequiredSex",
    operator: "equals",
    expected: true,
    effect: "hard_fail",
    reason: "This opportunity requires the recruiter's specified sex.",
  },
  {
    id: "permanent-or-semi-permanent-eyebrow",
    field: "hasPermanentOrSemiPermanentEyebrow",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason:
      "Permanent or semi-permanent eyebrow procedures are incompatible with this exam.",
  },
  {
    id: "permanent-or-semi-permanent-eyeliner",
    field: "hasPermanentOrSemiPermanentEyeliner",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason:
      "Permanent or semi-permanent eyeliner procedures are incompatible with this exam.",
  },
  {
    id: "permanent-or-semi-permanent-lips",
    field: "hasPermanentOrSemiPermanentLipProcedure",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason:
      "Permanent or semi-permanent lip procedures are incompatible with this exam.",
  },
  {
    id: "eyelash-extensions",
    field: "hasEyelashExtensions",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason: "Eyelash extensions are incompatible with this exam.",
  },
  {
    id: "persistent-visible-marks",
    field: "hasPersistentVisibleMarks",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason: "Persistent visible marks are incompatible with this exam.",
  },
  {
    id: "visible-tattoo-or-henna",
    field: "hasVisibleTattooOrHenna",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason: "Visible tattoos or henna are incompatible with this exam.",
  },
  {
    id: "visible-nail-art",
    field: "hasVisibleNailArt",
    operator: "equals",
    expected: false,
    effect: "hard_fail",
    reason: "Visible nail art is incompatible with this exam.",
  },
  {
    id: "remove-day-of-makeup",
    field: "wearsDayOfMakeup",
    operator: "equals",
    expected: false,
    effect: "reminder",
    reason: "Remove makeup before the appointment.",
  },
  {
    id: "remove-lenses",
    field: "wearsLenses",
    operator: "equals",
    expected: false,
    effect: "reminder",
    reason: "Remove lenses before the appointment.",
  },
  {
    id: "remove-accessories",
    field: "wearsAccessories",
    operator: "equals",
    expected: false,
    effect: "reminder",
    reason: "Remove accessories before the appointment.",
  },
  {
    id: "schedule-available",
    field: "isAvailable",
    operator: "equals",
    expected: true,
    effect: "hard_fail",
    reason: "This schedule is unavailable.",
  },
  {
    id: "bring-identity-document",
    field: "hasIdentityDocument",
    operator: "equals",
    expected: true,
    effect: "reminder",
    reason: "Bring an identity document to the appointment.",
  },
] satisfies readonly RuleDefinition[];
